/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'ember': '#d62b2b',
        'on-primary-fixed': '#410003',
        'on-primary': '#690007',
        'on-tertiary-container': '#fff3ed',
        'error-container': '#93000a',
        'on-primary-container': '#fff2f1',
        'surface-tint': '#ffb4ac',
        'surface-variant': '#353534',
        'on-primary-fixed-variant': '#93000e',
        'on-secondary-container': '#b5b5b2',
        'primary': '#ffb4ac',
        'tertiary': '#ffb784',
        'on-error-container': '#ffdad6',
        'surface-container': '#201f1f',
        'surface-container-highest': '#353534',
        'secondary': '#c7c7c3',
        'on-surface-variant': '#c9a8a5',
        'surface-container-low': '#1c1b1b',
        'tertiary-fixed-dim': '#ffb784',
        'tertiary-fixed': '#ffdcc6',
        'surface': '#131313',
        'on-tertiary-fixed-variant': '#713700',
        'on-surface': '#e5e2e1',
        'on-error': '#690005',
        'secondary-container': '#464744',
        'inverse-primary': '#bc141c',
        'tertiary-container': '#ab5b14',
        'surface-container-lowest': '#0e0e0e',
        'error': '#ffb4ab',
        'on-secondary-fixed-variant': '#464744',
        'on-tertiary': '#4f2500',
        'primary-fixed': '#ffdad6',
        'on-tertiary-fixed': '#301400',
        'background': '#131313',
        'inverse-surface': '#e5e2e1',
        'surface-container-high': '#2a2a2a',
        'on-secondary-fixed': '#1b1c1a',
        'secondary-fixed-dim': '#c7c7c3',
        'outline-variant': '#5c403d',
        'surface-dim': '#131313',
        'inverse-on-surface': '#313030',
        'primary-fixed-dim': '#ffb4ac',
        'outline': '#ab8885',
        'on-background': '#e5e2e1',
        'primary-container': '#d62b2b',
        'surface-bright': '#3a3939',
        'secondary-fixed': '#e3e2df',
        'on-secondary': '#30312e',
      },
      fontFamily: {
        headline: ['Epilogue', 'sans-serif'],
        body: ['Sora', 'sans-serif'],
        label: ['Sora', 'sans-serif'],
        bebas: ['"Bebas Neue"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      keyframes: {
        shine: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-20px) rotate(5deg)' },
        },
        'slide-in': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-out': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        shine: 'shine 3s infinite linear',
        float: 'float 6s ease-in-out infinite',
        'slide-in': 'slide-in 0.5s ease',
        shimmer: 'shimmer 2s infinite linear',
      },
    },
  },
  plugins: [],
};
